import localFont from "next/font/local";
import "./globals.css";

const workSans = localFont({
  src: [
    {
      path: "../assets/font/Work_Sans/static/WorkSans-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/font/Work_Sans/static/WorkSans-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/font/Work_Sans/static/WorkSans-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../assets/font/Work_Sans/static/WorkSans-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-work-sans",
  display: "swap",
});

export const metadata = {
  title: "Auto Naija Mart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${workSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
